# Generated by Django 5.1.7 on 2025-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('deploying_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('type', models.CharField(choices=[('פלטה', 'פלטה'), ('חתיכה', 'חתיכה')], max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
